# Generated by Django 5.2 on 2025-04-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video showcasing your project', null=True, upload_to='projects/videos/'),
        ),
    ]
